services:
  gitea_db:
      container_name: gitea_pg_db
      image: postgres:18
      restart: unless-stopped
      env_file:
        - ./.env
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        PGTZ: "UTC"
        TZ: "UTC"
      healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - "./container_data/gitea_db:/var/lib/postgresql"
      networks:
      - gitea

  gitea:
    image: gitea/gitea:1.26
    container_name: gitea
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=https://${ROOT_URL}
      - GITEA__server__HTTP_PORT=${WEB_PORT}
      - GITEA__server__SSH_PORT=${SSH_PORT}      

      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db:5432
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASSWORD}
    volumes:
      - ./container_data/gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
    - "${SSH_PORT}:22"
    - "${WEB_PORT}:3000"

    networks:
      - gitea

    depends_on:
      gitea_db:
        condition: service_healthy

networks:
  gitea:
    external: false
