services:
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./static_sites:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
