[global]
process-max=2
log-level-console=info

# will force checkpoint instead of waiting for checkpoint_timeout
start-fast=y
# only copy the files that are actually missing or different during restore
delta=y
compress-type=zst

repo1-retention-full-type=count
repo1-retention-full=2
repo1-bundle=y
repo1-block=y
repo1-type=posix
repo1-path=/var/lib/pgbackrest

repo2-retention-full-type=count
repo2-retention-full=2
repo2-bundle=y
repo2-block=y
repo2-type=s3
repo2-s3-bucket=backup-prod-bucket
repo2-s3-endpoint=s3.demo.com
repo2-s3-region=auto
repo2-s3-key=<your_access_key>
repo2-s3-key-secret=<your_secret_key>
repo2-path=/pgbackrest
repo2-s3-uri-style=path



[main]
pg1-path=/var/lib/postgresql/18/main
pg1-port=5432