wal_level = replica
archive_mode = on
# force PostgreSQL to archive periodically even if the WAL segment is not full
archive_timeout = 600
archive_command = 'pgbackrest --stanza=main archive-push %p'
