wal_level = replica
archive_mode = on
# PostgreSQL only archives a WAL segment when it is full (16MB)
# on a low-write DB this could take hours, leaving a large PITR gap
# this forces archiving every 300 seconds (5 min) even if segment is not full
# worst-case data loss window = 5 minutes
archive_timeout = 300
archive_command = 'pgbackrest --stanza=main archive-push %p'
