version: "3"
services:
  postgres_db:
    image: bitnami/postgresql:17
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: super-admin
      POSTGRES_PASSWORD: super-password
      POSTGRESQL_DATABASE: hms
      POSTGRESQL_TIMEZONE: "Asia/Dhaka"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/bitnami/postgresql"


volumes:
  postgres_data:
