services:
    mysql_db:
        image: bitnami/mysql:9.0
        restart: unless-stopped
        env_file:
            - ./.env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"
        volumes:
            - "mysql_data:/bitnami/mysql/data"

volumes:
    mysql_data:
