services:
  redis:
    image: "redis:8"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      start_period: 30s
      interval: 300s
      start_interval: 5s
      retries: 3
      timeout: 10s
      # allkeys-lru -> eviction policy when memory limit is reached
      # save 60 50 -> snapshot every 60 seconds if at least 50 writes
      # appendonly -> AOF saves from data loss due to crash(WAL like behaviour)
    command: |
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --bind 0.0.0.0
      --protected-mode yes
      --port 6379
      --save 60 50
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    env_file:
      - ./.env
    ports:
      - "6375:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network
      - app_network
volumes:
  redis_data:
networks:
  redis_network:
    external: true
  app_network:
    external: true
