services:
  redis_db:
    image: "redis:8"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      - redis-server
      - "--requirepass"
      - "${REDIS_PASSWORD}"
    env_file:
      - ./.env
    ports:
      - "6377:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis_data:
