version: "3"
services:
  app:
    build:
      context: .
    env_file:
      - .env.dev
    ports:
      - "3000:3020"
    volumes:
      - "app_data_devsfleet:/node-app"

volumes:
  app_data_devsfleet:
